name-template: 'v$RESOLVED_VERSION 🚀'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: '✨ New Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '📱 Mobile Improvements'
    labels:
      - 'mobile'
      - 'responsive'
      - 'pwa'
  - title: '⚡ Performance'
    labels:
      - 'performance'
      - 'optimization'
  - title: '🔒 Security'
    labels:
      - 'security'
      - 'vulnerability'
  - title: '📚 Documentation'
    labels:
      - 'documentation'
      - 'docs'
  - title: '🧪 Testing'
    labels:
      - 'testing'
      - 'test'
  - title: '🔧 Maintenance'
    labels:
      - 'maintenance'
      - 'refactor'
      - 'deps'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'

change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels:
      - 'breaking'
      - 'major'
  minor:
    labels:
      - 'feature'
      - 'enhancement'
      - 'minor'
  patch:
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'documentation'
      - 'patch'

template: |
  ## 🎯 What's Changed

  $CHANGES

  ## 📱 Mobile Support
  - ✅ iOS Safari tested
  - ✅ Android Chrome tested  
  - ✅ PWA functionality verified
  - ✅ Touch interactions optimized

  ## 🧪 Testing
  - ✅ Unit tests passing
  - ✅ E2E tests passing
  - ✅ Mobile tests passing
  - ✅ Smart contract tests passing

  ## 🚀 Deployment
  - ✅ Auto-deployed to Vercel
  - ✅ Environment variables updated
  - ✅ Performance metrics verified

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

  ---
  
  **🎮 Try it now**: [Live Demo](https://your-deployment-url.vercel.app)
  
  **📱 Mobile**: Optimized for all devices, installable as PWA