name: Bug Report
description: Reportar un bug o error en la aplicación
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Gracias por reportar este bug. Por favor, proporciona toda la información posible.

  - type: input
    id: browser
    attributes:
      label: Browser
      description: ¿Qué browser estás usando?
      placeholder: Chrome 120, Firefox 115, Safari 17
    validations:
      required: true

  - type: input
    id: wallet
    attributes:
      label: Wallet
      description: ¿Qué wallet estás usando?
      placeholder: Phantom, Solflare, Backpack
    validations:
      required: false

  - type: textarea
    id: steps
    attributes:
      label: Pasos para reproducir
      description: Describe paso a paso cómo reproducir el bug
      placeholder: |
        1. Abrir la aplicación
        2. Ejecutar comando 'connect phantom'
        3. Ver error en consola
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Comportamiento esperado
      description: ¿Qué esperabas que pasara?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Comportamiento actual
      description: ¿Qué está pasando en realidad?
    validations:
      required: true

  - type: textarea
    id: console
    attributes:
      label: Errores de consola
      description: Si hay errores en la consola del browser, cópialos aquí
      render: javascript

  - type: textarea
    id: additional
    attributes:
      label: Información adicional
      description: Cualquier otra información relevante
